"""FIBR-0159 — Flatpak / Flathub packaging.

Enforces tests/features/flatpak_packaging/spec.md. No real Flathub build:

  * manifest / deps scrape (INV-1/2/3/4/7) — structural YAML-key-anchored parse of
    packaging/flatpak/io.github.milnet01.finbreak.yaml + python3-deps.yaml, mirroring
    tests/features/obs_packaging/test_obs_packaging.py.
  * runtime assertion (INV-6, INV-8) — the Flatpak-launch updater-inert gate
    (reused predicate) and the _kde_wayland() Flatpak window-centering gate.
  * metainfo validate (INV-5) — skip-if-absent (appstreamcli not in CI).

python3-deps.yaml is GENERATED by generate-pip-sources.sh; scrape tests over it
SKIP when it is absent, so the gate stays green before first generation (§ 4/§ 5).

No network, no real Flatpak build, no financial data.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import tomllib
from pathlib import Path
from typing import Any

import pytest
import yaml

pytestmark = pytest.mark.features

_REPO_ROOT = Path(__file__).resolve().parents[3]
_FLATPAK = _REPO_ROOT / "packaging" / "flatpak"
_OBS = _REPO_ROOT / "packaging" / "obs"
_PYPROJECT = _REPO_ROOT / "pyproject.toml"

APP_ID = "io.github.milnet01.finbreak"
_MANIFEST = _FLATPAK / f"{APP_ID}.yaml"
_DEPS = _FLATPAK / "python3-deps.yaml"
_METAINFO = _OBS / f"{APP_ID}.metainfo.xml"
_GEN_SCRIPT = _FLATPAK / "generate-pip-sources.sh"
_BUILD_SCRIPT = _FLATPAK / "flatpak-build.sh"
_FLATHUB_JSON = _FLATPAK / "flathub.json"

# Concrete CPU arches a manylinux platform tag can name (the ones Flathub builds).
# A wheel platform tag is `<arch>` for the pure-Python `any` case (skipped) or ends
# in one of these for a native manylinux wheel.
_KNOWN_ARCHES = ("x86_64", "aarch64", "armv7l", "i686", "ppc64le", "s390x")

# INV-2 — the ENUMERATED sandbox allowlist (§ 3.4). Every finish-args entry must be
# one of these; anything else — a --share=network, any --filesystem=, any
# --talk-name= — fails the test. The coverage boundary is explicit, not a blocklist.
_FINISH_ARGS_ALLOWLIST = frozenset(
    {
        "--socket=wayland",
        "--socket=fallback-x11",
        "--share=ipc",
        "--device=dri",
    }
)


# --------------------------------------------------------------------------- #
# YAML helpers — structural walks (INV-1..4/7 are key-anchored, not substring).
# --------------------------------------------------------------------------- #
def _load(path: Path) -> Any:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _iter_scalars(obj: Any):
    """Every scalar (str/int/float) leaf in a nested dict/list — for the INV-1
    KDE/BaseApp-absence and INV-4 semver checks over parsed VALUES (comments are
    stripped by the YAML parser, so a comment mention never false-positives)."""
    if isinstance(obj, dict):
        for v in obj.values():
            yield from _iter_scalars(v)
    elif isinstance(obj, list):
        for v in obj:
            yield from _iter_scalars(v)
    else:
        yield obj


def _iter_modules(obj: Any):
    """Every module-like dict (one carrying a ``sources`` key) anywhere in a
    manifest/deps structure — recursing whatever shape flatpak-pip-generator emits
    (a flat single module, or nested ``modules[].sources[]`` per package, § 3.6)."""
    if isinstance(obj, dict):
        if "sources" in obj:
            yield obj
        for v in obj.values():
            yield from _iter_modules(v)
    elif isinstance(obj, list):
        for v in obj:
            yield from _iter_modules(v)


def _source_filename(src: dict) -> str:
    """The wheel/sdist basename for a pip source — from an explicit filename field
    or the tail of the pinned URL."""
    for key in ("filename", "dest-filename"):
        if isinstance(src.get(key), str):
            return src[key]
    url = src.get("url", "")
    return url.rsplit("/", 1)[-1] if isinstance(url, str) else ""


def _require_deps() -> Any:
    if not _DEPS.exists():
        pytest.skip("python3-deps.yaml not generated yet (generate-pip-sources.sh)")
    return _load(_DEPS)


# --------------------------------------------------------------------------- #
# INV-1 — freedesktop runtime, pinned branch, no distro/KDE Qt.
# --------------------------------------------------------------------------- #
def test_INV1_freedesktop_runtime_pinned() -> None:
    m = _load(_MANIFEST)
    assert m["runtime"] == "org.freedesktop.Platform"
    assert m["sdk"] == "org.freedesktop.Sdk"
    # A REAL pin — two-segment branch, not master/beta/absent.
    assert re.fullmatch(r"\d+\.\d+", str(m["runtime-version"])), (
        f"runtime-version {m['runtime-version']!r} is not a pinned N.N branch"
    )
    # No KDE runtime / PySide BaseApp anywhere in the parsed values (§ 3.1/§ 7).
    for val in _iter_scalars(m):
        if isinstance(val, str):
            assert "org.kde." not in val, f"KDE runtime reference in manifest: {val!r}"
            assert "BaseApp" not in val, (
                f"PySide BaseApp reference in manifest: {val!r}"
            )


# --------------------------------------------------------------------------- #
# INV-2 — network-free + filesystem-free sandbox (the security contract).
# --------------------------------------------------------------------------- #
def test_INV2_sandbox_is_minimal() -> None:
    m = _load(_MANIFEST)
    finish_args = m.get("finish-args", [])
    assert finish_args, "manifest has no finish-args"
    for arg in finish_args:
        assert arg in _FINISH_ARGS_ALLOWLIST, (
            f"finish-arg {arg!r} is not in the enumerated allowlist — a "
            "network/filesystem/talk-name permission would widen the sandbox"
        )


def test_INV2_no_network_filesystem_or_talkname() -> None:
    # Belt-and-suspenders over the raw text: even a COMMENTED-in permission line
    # shouldn't creep in as an active entry. Scan parsed finish-args explicitly.
    m = _load(_MANIFEST)
    for arg in m.get("finish-args", []):
        assert not arg.startswith("--share=network")
        assert not arg.startswith("--filesystem=")
        assert not arg.startswith("--talk-name=")


# --------------------------------------------------------------------------- #
# INV-3 — pip sources sha256-pinned, offline, single-ABI.
# --------------------------------------------------------------------------- #
def test_INV3a_sources_pinned_and_offline() -> None:
    deps = _require_deps()
    saw_source = False
    for mod in _iter_modules(deps):
        for src in mod["sources"]:
            if not isinstance(src, dict) or src.get("type") not in ("file", "archive"):
                continue
            saw_source = True
            sha = src.get("sha256", "")
            assert re.fullmatch(r"[0-9a-f]{64}", str(sha)), (
                f"source {_source_filename(src)!r} lacks a 64-hex sha256"
            )
        for cmd in mod.get("build-commands", []):
            if "pip3 install" in cmd or "pip install" in cmd:
                assert "--no-index" in cmd, f"pip install without --no-index: {cmd!r}"
    assert saw_source, "no pinned file/archive sources found in python3-deps.yaml"


def test_INV3b_no_build_time_network() -> None:
    deps = _require_deps()
    for mod in _iter_modules(deps):
        build_args = (mod.get("build-options") or {}).get("build-args", [])
        assert "--share=network" not in build_args, (
            f"module {mod.get('name')!r} grants build-time network"
        )


def test_INV3c_single_cpython_abi() -> None:
    deps = _require_deps()
    minors: set[str] = set()
    for mod in _iter_modules(deps):
        for src in mod["sources"]:
            if not isinstance(src, dict):
                continue
            name = _source_filename(src)
            if not name.endswith(".whl"):
                continue
            fields = name[: -len(".whl")].split("-")
            if len(fields) < 5:
                continue
            abitag = fields[-2]  # abitag field — NOT a pytag substring scan
            m = re.fullmatch(r"cp(\d+)", abitag)
            if m:  # genuinely per-minor (cp313); abi3 / none are excluded
                minors.add(m.group(1))
    assert len(minors) <= 1, (
        f"mixed CPython ABIs in python3-deps.yaml: {sorted(minors)}"
    )


# --------------------------------------------------------------------------- #
# INV-9 — flathub.json restricts the build to exactly the closure's arches.
# The pinned wheels are x86_64-only (generate-pip-sources.sh --wheel-arches=x86_64),
# but Flathub's buildbot builds EVERY arch by default — so an aarch64 build would
# `pip install --no-index` an x86_64 wheel and fail. flathub.json's `only-arches`
# must equal the concrete arch set the wheel filenames carry, so the two can never
# drift (widen the wheels ⟹ must widen only-arches, and vice versa).
# --------------------------------------------------------------------------- #
def _closure_arches(deps: Any) -> set[str]:
    """The set of concrete CPU arches the pinned wheels target (pure-Python
    `*-none-any` wheels and the sdist are arch-independent — they contribute none)."""
    arches: set[str] = set()
    for mod in _iter_modules(deps):
        for src in mod["sources"]:
            if not isinstance(src, dict):
                continue
            name = _source_filename(src)
            if not name.endswith(".whl"):
                continue
            platform_tags = name[: -len(".whl")].split("-")[-1]  # trailing platform tag
            for tag in platform_tags.split("."):
                for arch in _KNOWN_ARCHES:
                    if tag.endswith(arch):
                        arches.add(arch)
    return arches


def test_INV9_flathub_json_restricts_to_closure_arches() -> None:
    assert _FLATHUB_JSON.exists(), (
        "packaging/flatpak/flathub.json is missing — without `only-arches` Flathub "
        "builds every arch and the aarch64 build fails on the x86_64-only closure"
    )
    config = json.loads(_FLATHUB_JSON.read_text(encoding="utf-8"))
    only_arches = config.get("only-arches")
    assert isinstance(only_arches, list) and only_arches, (
        "flathub.json needs a non-empty only-arches list"
    )

    deps = _require_deps()
    want = _closure_arches(deps)
    assert want, "no concrete-arch wheels found in python3-deps.yaml"
    assert set(only_arches) == want, (
        f"flathub.json only-arches {sorted(only_arches)} != wheel-closure arches "
        f"{sorted(want)} — restrict Flathub to exactly what the pinned wheels cover"
    )


# --------------------------------------------------------------------------- #
# INV-4 — identity + version single-source (new Flatpak-side legs only).
# --------------------------------------------------------------------------- #
def test_INV4_identity_and_version() -> None:
    m = _load(_MANIFEST)
    assert m["id"] == APP_ID
    assert _MANIFEST.name == f"{APP_ID}.yaml", "manifest filename stem must be app-ID"
    # command is the bare console script — NOT the app-ID (§ 3.3).
    assert m["command"] == "finbreak"

    # The finbreak module's git source pins an immutable 40-hex commit (§ 3.8).
    git_commit = None
    for mod in _iter_modules(m):
        if isinstance(mod, dict) and mod.get("name") == "finbreak":
            for src in mod["sources"]:
                if isinstance(src, dict) and src.get("type") == "git":
                    git_commit = src.get("commit")
    assert git_commit is not None, "finbreak module has no git source with a commit"
    assert re.fullmatch(r"[0-9a-f]{40}", str(git_commit)), (
        f"git commit {git_commit!r} is not a 40-hex sha (a tag-only pin fails)"
    )

    # No hand-typed version: no manifest key VALUE is a bare 3-segment semver
    # (runtime-version is 2-segment; the tag carries a leading 'v') — a structural
    # walk, not a raw-text sweep that inline version comments would false-positive.
    for val in _iter_scalars(m):
        assert not re.fullmatch(r"\d+\.\d+\.\d+", str(val)), (
            f"bare semver {val!r} in a manifest value — version must ride the git tag"
        )


# --------------------------------------------------------------------------- #
# INV-5 — metainfo validates for Flathub (skip-if-absent — appstreamcli not in CI).
# --------------------------------------------------------------------------- #
def test_INV5_metainfo_validates() -> None:
    tool = shutil.which("appstreamcli")
    if tool is None:
        pytest.skip("appstreamcli not installed (manual pre-submit check, § 5)")
    result = subprocess.run(  # noqa: S603 — fixed argv, no shell
        [tool, "validate", "--no-net", str(_METAINFO)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stdout + result.stderr


# --------------------------------------------------------------------------- #
# INV-6 — self-updater inert under a Flatpak launch ($APPIMAGE unset).
# Reuses the obs_packaging updater-inert predicate (rule 3).
# --------------------------------------------------------------------------- #
def test_INV6_updater_inert_under_flatpak(monkeypatch: pytest.MonkeyPatch) -> None:
    from finbreak.services import update_installer

    monkeypatch.delenv("APPIMAGE", raising=False)
    monkeypatch.setattr(update_installer.sys, "platform", "linux")
    monkeypatch.delattr(update_installer.sys, "frozen", raising=False)

    assert update_installer.detect_installer() is None
    assert update_installer.is_update_supported() is False


# --------------------------------------------------------------------------- #
# INV-7 — PySide6 pin is the single Qt source.
# --------------------------------------------------------------------------- #
def test_INV7_pyside6_pin_matches_pyproject() -> None:
    deps = _require_deps()
    pyproject = tomllib.loads(_PYPROJECT.read_text(encoding="utf-8"))
    pinned = next(
        d for d in pyproject["project"]["dependencies"] if d.startswith("PySide6==")
    )
    want_version = pinned.split("==", 1)[1]  # 6.11.1

    found = None
    for mod in _iter_modules(deps):
        for src in mod["sources"]:
            if not isinstance(src, dict):
                continue
            name = _source_filename(src)
            # Wheel: PySide6-6.11.1-cp313-...whl (case-insensitive dist name).
            m = re.match(r"(?i)pyside6-([0-9][^-]*)-", name)
            if m:
                found = m.group(1)
    assert found is not None, "no PySide6 wheel found in python3-deps.yaml"
    assert found == want_version, (
        f"PySide6 wheel {found} != pyproject pin {want_version} (Qt source drifted)"
    )


# --------------------------------------------------------------------------- #
# INV-8 — window-centering disabled under Flatpak (the definite src/ change).
# --------------------------------------------------------------------------- #
def test_INV8_centering_disabled_under_flatpak(monkeypatch: pytest.MonkeyPatch) -> None:
    from finbreak.ui import main_window

    # Under Flatpak + KDE-Wayland, the org.kde.KWin call is unreachable (§ 3.5), so
    # _kde_wayland() must return False — the single chokepoint _center_supported()
    # and _center_window() both consult — even though the env looks like KDE Wayland.
    monkeypatch.setattr(main_window, "_in_flatpak", lambda: True)
    monkeypatch.setattr(main_window, "_is_wayland", lambda: True)
    monkeypatch.setenv("XDG_CURRENT_DESKTOP", "KDE")

    assert main_window._kde_wayland() is False, "Flatpak gate must disable KWin path"
    assert main_window._center_supported() is False, (
        "Center window must be disabled under Flatpak (no dead click)"
    )


def test_INV8_gate_is_flatpak_specific(monkeypatch: pytest.MonkeyPatch) -> None:
    # Guard the guard: WITHOUT the Flatpak marker, KDE Wayland still supports
    # centering (the gate is Flatpak-specific, not a blanket disable).
    from finbreak.ui import main_window

    monkeypatch.setattr(main_window, "_in_flatpak", lambda: False)
    monkeypatch.setattr(main_window, "_is_wayland", lambda: True)
    monkeypatch.setenv("XDG_CURRENT_DESKTOP", "KDE")

    assert main_window._kde_wayland() is True
    assert main_window._center_supported() is True


# --------------------------------------------------------------------------- #
# Recipe files exist (the § 6 implementation surface).
# --------------------------------------------------------------------------- #
def test_recipe_files_present() -> None:
    required = (
        _MANIFEST,
        _GEN_SCRIPT,
        _BUILD_SCRIPT,
        _FLATHUB_JSON,
        _FLATPAK / "README.md",
    )
    for path in required:
        assert path.exists(), f"missing packaging/flatpak file: {path.name}"
